spring:
  application:
    name: t1-java-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/t1_demo
    username: postgres
    password: "0000"
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    default-schema: t1_demo
    change-log: db/changelog/db.changelog-master.xml

logging:
  level:
    ROOT: INFO
    ru.t1.java.demo.controller.ClientController: DEBUG

t1:
  scan-path: ru.t1.java.demo
  kafka:
    bootstrap:
      server: localhost:9092
    consumer:
      group-id: t1-demo
      account-id: account-listener
      transaction-id: transaction-listener
      max.poll.records: 10
    producer:
      enable: true
    topic:
      client_registration: t1_demo_client_registration
      client_id_registered: t1_demo_client_registered
      client_transactions: t1_demo_client_transactions
      accounts: t1_demo_accounts
      transactions: t1_demo_transactions
      metric_trace: t1_demo_metric_trace
      error_trace: t1_demo_error_trace
    listener:
      poll-timeout: 1000

metric:
  execution:
    time:
      threshold: 1000
